import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../components/Button'
import Upgrade from '../components/Upgrade'
import styles from '../styles/Home.module.scss'
import { useEffect, useState } from 'react';

interface Upgrade {
	title: string;
	description: string;
	clickIncrease: number;
	perSecondIncrease: number;
	price: number;
}

const upgradesClick: Array<Upgrade> = [
	{
		title: "Rawas",
		description: "Gives you another mouse",
		clickIncrease: 10,
		perSecondIncrease: 0,
		price: 25
	},
	{
		title: "Fish",
		description: "Gives you another mouse",
		clickIncrease: 20,
		perSecondIncrease: 0,
		price: 50
	},
	{
		title: "2 Mice",
		description: "Gives you a mouse but 50",
		clickIncrease: 50,
		perSecondIncrease: 0,
		price: 100
	},
	{
		title: "3 Mice",
		description: "Gives you a mouse but 100",
		clickIncrease: 100,
		perSecondIncrease: 0,
		price: 200
	},
	{
		title: "4 Shark",
		description: "Gives you a mouse but 400",
		clickIncrease: 400,
		perSecondIncrease: 0,
		price: 800
	}
]

const upgradesInterval: Array<Upgrade> = [
	{
		title: "Mouse 2.0",
		description: "Gives you more clickage",
		clickIncrease: 0,
		perSecondIncrease: 1,
		price: 10
	},
	{
		title: "Cat",
		description: "Gives you more clickage",
		clickIncrease: 0,
		perSecondIncrease: 5,
		price: 100
	},
	{
		title: "Tiger",
		description: "Like a cat but big",
		clickIncrease: 0,
		perSecondIncrease: 10,
		price: 500
	},
	{
		title: "Dinasour",
		description: "Big creature",
		clickIncrease: 0,
		perSecondIncrease: 20,
		price: 1000
	},
	{
		title: "Megalodon",
		description: "Big creature but gives you 500 clickage",
		clickIncrease: 0,
		perSecondIncrease: 500,
		price: 1500
	}
]

const upgradesPets: Array<Upgrade> = [
	{
		title: "Dragon",
		description: "Gives you mouse 500 and clickage 300",
		clickIncrease: 500,
		perSecondIncrease: 300,
		price: 1000
	},
	{
		title: "Shark",
		description: "Gives you mouse 1000 and clickage 500",
		clickIncrease: 1000,
		perSecondIncrease: 500,
		price: 1500
	}
]

const basicPets: Array<Upgrade> = [
	{
		title: "Cat",
		description: "Gives you mouse 10 and clickage 20",
		clickIncrease: 10,
		perSecondIncrease: 20,
		price: 20
	},
	{
		title: "Dog",
		description: "Gives you mouse 50 and clickage 100",
		clickIncrease: 50,
		perSecondIncrease: 100,
		price: 50
	}
]

const mythicalPets: Array<Upgrade> = [
	{
		title: "Bull of hell",
		description: "Gives you mouse 10,000 and clickage 20,000",
		clickIncrease: 10000,
		perSecondIncrease: 20000,
		price: 2000
	},
	{
		title: "Lighting",
		description: "Gives you mouse 100000 and clickage 200000",
		clickIncrease: 100000,
		perSecondIncrease: 200000,
		price: 2500
	}
]

const rarePets: Array<Upgrade> = [
	{
		title: "Bull",
		description: "Gives you mouse 500 and clickage 400",
		clickIncrease: 500,
		perSecondIncrease: 400,
		price: 500
	}
]

const Home: NextPage = () => {
	const [clicks, setClicks] = useState(1);
	const [mouseClicks, setMouseClicks] = useState(1);
	const [clicksPerSecond, setClicksPerSecond] = useState(0);
	const [hasStarted, setHasStarted] = useState(false);
	const buttonClick = () => {
		setClicks(c => c + mouseClicks);
	}

	const increase = () => {
		setInterval(() => {
			setClicksPerSecond(s => {
				setClicks(c => c + s);
				return s;
			})
			setHasStarted(true);
		}, 1000);
	}

	useEffect(() => {
		if (!hasStarted) {
			increase()
		}
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Clicker Game</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={styles.upgradeColumn}>
					<h2>Upgrades</h2>

					{upgradesClick.map((upgrade, i) => <Upgrade
						title={upgrade.title}
						description={upgrade.description}
						clickIncrease={upgrade.clickIncrease}
						perSecondIncrease={upgrade.perSecondIncrease}
						price={upgrade.price}
						setMouseClicks={setMouseClicks}
						setClicksPerSecond={setClicksPerSecond}
						setClicks={setClicks}
						clicks={clicks}
						key={i}
					/>)}
					<h2>Basic Pets</h2>

					{basicPets.map((upgrade, i) => <Upgrade
						title={upgrade.title}
						description={upgrade.description}
						clickIncrease={upgrade.clickIncrease}
						perSecondIncrease={upgrade.perSecondIncrease}
						price={upgrade.price}
						setMouseClicks={setMouseClicks}
						setClicksPerSecond={setClicksPerSecond}
						setClicks={setClicks}
						clicks={clicks}
						key={i}
					/>)}

					<h2>Rare Pets</h2>

					{rarePets.map((upgrade, i) => <Upgrade
						title={upgrade.title}
						description={upgrade.description}
						clickIncrease={upgrade.clickIncrease}
						perSecondIncrease={upgrade.perSecondIncrease}
						price={upgrade.price}
						setMouseClicks={setMouseClicks}
						setClicksPerSecond={setClicksPerSecond}
						setClicks={setClicks}
						clicks={clicks}
						key={i}
					/>)}
				</div>

				<div className={styles.mainContainer}>
					<div className={styles.clickContainer}>
						<h2>Clicker Game</h2>
						<h1 className={styles.clickIndicator}>{clicks}</h1>
						<Button onClick={buttonClick} />
					</div>
				</div>
				<div className={styles.upgradeColumn}>
					<h2>More Upgrades</h2>

					{upgradesInterval.map((upgrade, i) => <Upgrade
						title={upgrade.title}
						description={upgrade.description}
						clickIncrease={upgrade.clickIncrease}
						perSecondIncrease={upgrade.perSecondIncrease}
						price={upgrade.price}
						setMouseClicks={setMouseClicks}
						setClicksPerSecond={setClicksPerSecond}
						setClicks={setClicks}
						clicks={clicks}
						key={i}
					/>)}
					<h2> Legendary Pets</h2>
					{upgradesPets.map((upgrade, i) => <Upgrade
						title={upgrade.title}
						description={upgrade.description}
						clickIncrease={upgrade.clickIncrease}
						perSecondIncrease={upgrade.perSecondIncrease}
						price={upgrade.price}
						setMouseClicks={setMouseClicks}
						setClicksPerSecond={setClicksPerSecond}
						setClicks={setClicks}
						clicks={clicks}
						key={i}
					/>)}
					<h2>Mythical Pets</h2>
					{mythicalPets.map((upgrade, i) => <Upgrade
						title={upgrade.title}
						description={upgrade.description}
						clickIncrease={upgrade.clickIncrease}
						perSecondIncrease={upgrade.perSecondIncrease}
						price={upgrade.price}
						setMouseClicks={setMouseClicks}
						setClicksPerSecond={setClicksPerSecond}
						setClicks={setClicks}
						clicks={clicks}
						key={i}
					/>)}
				</div>
			</main>
		</div>
	)
}

export default Home
